name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  export-postman-data:
    name: Export Postman Collection and Environment
    runs-on: ubuntu-latest
    env:
      POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      CollectionID: ${{ secrets.PMCOLLECTIONID }}
      ENVIRONEMENTID: ${{ secrets.PMENVIRONMENTID }}
      ENVIRONMENT_NAME: "pm_environment.json"
      COLLECTION_NAME: "postman_collection.json"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Alpine tools
        run: |
          sudo apt-get update
          sudo apt-get install -y curl bash
          chmod +x ./export_postman_collection_environment.sh
          mkdir -p artifacts/
          ./export_postman_collection_environment.sh
          cat artifacts/${{ env.ENVIRONMENT_NAME }}

      - name: Upload exported artifacts
        uses: actions/upload-artifact@v4
        with:
          name: postman-artifacts
          path: artifacts/**

  run-api-tests:
    name: Run API Tests
    runs-on: ubuntu-latest
    needs: export-postman-data
    env:
      COLLECTION_NAME: "postman_collection.json"
      ENVIRONMENT_NAME: "pm_environment.json"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download exported artifacts
        uses: actions/download-artifact@v4
        with:
          name: postman-artifacts
          path: artifacts

      - name: Install Newman
        run: |
          npm install -g newman newman-reporter-htmlextra

      - name: Run Newman Collection
        run: |
          pwd
          ls -la artifacts
          newman run "artifacts/${{ env.COLLECTION_NAME }}" -e "artifacts/${{ env.ENVIRONMENT_NAME }}" -r cli,htmlextra --reporter-htmlextra-export "artifacts/Reports/Test-Report.html" --bail false

      - name: Upload API Test Report
        uses: actions/upload-artifact@v4
        with:
          name: api-report
          path: artifacts/Reports/**